[versions]
kotlin = "2.2.21"
spring-boot = "4.0.0"
spring-dependencyManagement = "1.1.7"
ktor = "3.3.3"
dgsBom = "11.0.0"
dgsCodegen = "8.3.0"
kotlinxSerializationBom = "1.9.0"
gcloud-firestore = "3.34.0"
detekt = "2.0.0-alpha.1"
graalvmNative = "0.11.3"
caffeine = "3.2.3"
scrapeit = "1.3.0-alpha.2"
toolchainsResolver = "1.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-powerAssert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
kotlin-noArg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependencyManagement" }
dgsCodegen = { id = "com.netflix.dgs.codegen", version.ref = "dgsCodegen" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
graalvmNative = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNative" }

[libraries]
detektKtlintWrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt"}
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-xml = { module = "io.ktor:ktor-serialization-kotlinx-xml", version.ref = "ktor" }
dgs-bom = { module = "com.netflix.graphql.dgs:graphql-dgs-platform-dependencies", version.ref = "dgsBom" }
dgs-starter = { module = "com.netflix.graphql.dgs:dgs-starter"}
gcloud-firestore = { module = "com.google.cloud:google-cloud-firestore", version.ref = "gcloud-firestore" }
kotlinx-serialization-bom = { module = "org.jetbrains.kotlinx:kotlinx-serialization-bom", version.ref = "kotlinxSerializationBom" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
scrapeit = { module = "it.skrape:skrapeit", version.ref = "scrapeit" }
